name: Sync Specific Branch

on:
  workflow_dispatch: # Allows manual trigger

jobs:
  sync-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Your Repository
        uses: actions/checkout@v4
        with:
          ref: main

          
      - name: Configure Git User
        run: |
          git config user.email "akuntrial042@gmail.com"
          git config user.name "JJ-Coffee"
          

      - name: Add Upstream Repository
        run: |
          git remote add upstream https://github.com/Saikrishna1504/kernel_xiaomi_mt6785.git
          git fetch upstream

      - name: Merge Specific Branch
        run: |
          git checkout main
          git merge upstream/vic --allow-unrelated-histories

      - name: Push Changes
        run: |
          git push origin main
          
